/*
 * This Scala Testsuite was auto generated by running 'gradle init --type scala-library'
 * by 'Marty' at '2/9/14 8:41 PM' with Gradle 1.10
 *
 * @author Marty, @date 2/9/14 8:41 PM
 */

import org.scalatest.FunSuite
import org.junit.runner.RunWith
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class LibrarySuite extends FunSuite {
  test("someLibraryMethod is always true") {
    def library = new Library()
    assert(library.someLibraryMethod)
  }
}
