/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'Marty' at '2/9/14 8:38 PM' with Gradle 1.10
 *
 * @author Marty, @date 2/9/14 8:38 PM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
