/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'Marty' at '2/9/14 8:38 PM' with Gradle 1.10
 *
 * @author Marty, @date 2/9/14 8:38 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
