/*
 * This Scala source file was auto generated by running 'gradle buildInit --type scala-library'
 * by 'Marty' at '2/9/14 8:41 PM' with Gradle 1.10
 *
 * @author Marty, @date 2/9/14 8:41 PM
 */
class Library {
  def someLibraryMethod(): Boolean = true
}
