/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Marty' at '2/9/14 8:40 PM' with Gradle 1.10
 *
 * @author Marty, @date 2/9/14 8:40 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
